name: CICD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
  actions: read
  contents: read
  packages: write
  id-token: write
  security-events: write
  

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Java and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: Build and test
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test coverage verification
        run: ./gradlew jacocoTestCoverageVerification

      - name: Integration test
        run: ./gradlew integrationTest --tests '*IntegrationTest'

      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results
          path: record-controlled-work-service/build/test-results
          retention-days: 14

      - name: Upload checkstyle report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: checkstyle-report
          path: record-controlled-work-service/build/reports/checkstyle
          retention-days: 14

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-report
          path: record-controlled-work-service/build/reports/tests
          retention-days: 14

      - name: Upload jacoco coverage report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jacoco-coverage-report
          path: record-controlled-work-service/build/reports/jacoco
          retention-days: 14

  vulnerability-report:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Fetch Snyk OAuth Token
        uses: ./.github/actions/snyk-auth

      - name: Set up Java and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: Setup Snyk
        uses: snyk/actions/setup@12140f4059e244892ae643824a95459a102120dd # master

      - name: Run Snyk to check app for vulnerabilities
        run: snyk monitor --severity-threshold=high
        continue-on-error: true

      - name: Generate sarif Snyk report
        run: snyk test --sarif-file-output=snyk-app.sarif
        continue-on-error: true

      # Fix/hack for Snyk's sarif file to avoid this error uploading to GitHub.
      # See https://github.com/github/codeql-action/issues/2187 for more context.
      - name: Fix undefined values
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk-app.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1
        with:
          sarif_file: snyk-app.sarif

  build-push-deploy-uat:
    if: "!(github.event_name == 'pull_request' && github.actor == 'renovate[bot]')"
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/cp-build-push-deploy.yml@3b61534ec28baab6171267eb56187bb597e89d45 # main
    with:
      app_name: laa-record-controlled-work-api
      helm_chart: ./laa-generic-helm-chart
      environment: uat
      helm_release_name: laa-record-controlled-work-api
      helm_values_path: ./helm/values/uat.yml
      k8s_service_account: rcw-api-github-action-service-account
      dockerfile_requires_git: true
    secrets: inherit