# Workflow: SCA ⚡️
# Description:
#   Scheduled and on-demand Security Composition Analysis run.
#   - Triggers: daily cron, PRs to main, workflow dispatch, branch protection rule.
#   - sca: Checks out repo, installs node, runs npm ci, executes ministryofjustice/sca action with dependency review configuration.

name: SCA ⚡️
run-name: Software Composition Analysis ⚡️

on:
  schedule:
    - cron: "0 6 * * *"

  pull_request:
    branches: ["main"]

  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    steps:
      - name: Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Set up Java and Gradle"
        uses: ./.github/actions/setup-java-gradle

      - name: "Build classes without running tests"
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./gradlew clean assemble testClasses integrationTestClasses

      - name: ⚡️ SCA
        uses: ministryofjustice/devsecops-actions/sca@86248cec9a6bb1fd4dabc08a05178e0650d3af4f # Feature branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Container Scanning
          docker-images-file: ${{ github.workspace }}/docker-images.json

          # Dependency Management
          renovate: "false"

          # Custom Configurations
        #   codeql-config-file: ".github/config/codeql.yml"
          codeql-languages: "java"
          codeql-upload-findings: "always"